# Generated by Django 6.0.4 on 2026-04-20 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('COD_PROV', models.CharField(blank=True, max_length=15, null=True)),
                ('NOM_PROV', models.CharField(max_length=20, unique=True)),
                ('EMAIL_PROV', models.CharField(max_length=60, unique=True)),
                ('TEL_PROV', models.CharField(blank=True, max_length=40, null=True)),
                ('NIT_PROV', models.CharField(blank=True, max_length=40, null=True)),
                ('EST_PROV', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_PRO', models.CharField(blank=True, max_length=15, null=True)),
                ('NOM_PRO', models.CharField(max_length=200)),
                ('PRECIO_COMPRA_PRO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PRECIO_VENTA_PRO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PRECIO_VENTA_UNIDAD_PRO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DESC_PRO', models.CharField(blank=True, max_length=200, null=True)),
                ('EST_PRO', models.BooleanField(default=True)),
                ('id_prov', models.BigIntegerField()),
                ('IMAGEN_PRO', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('COD_USU', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=255)),
                ('NOM_2_USU', models.CharField(max_length=100, null=True)),
                ('AP_PAT_USU', models.CharField(max_length=100)),
                ('AP_MAT_USU', models.CharField(max_length=100)),
                ('CEL_USU', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('EST_USU', models.BooleanField(default=True)),
                ('AVATAR_USU', models.CharField(max_length=200, null=True)),
                ('role_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_CLI', models.CharField(blank=True, max_length=15, null=True)),
                ('CI_CLI', models.CharField(max_length=20, unique=True)),
                ('FECHA_NAC_CLI', models.DateField(blank=True, null=True)),
                ('TIPO_CLI', models.CharField(blank=True, max_length=25, null=True)),
                ('NIT_CLI', models.CharField(blank=True, max_length=40, null=True)),
                ('EST_CLI', models.BooleanField(default=True)),
                ('id_usu', models.ForeignKey(db_column='id_usu', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANT_CAR', models.IntegerField(blank=True, null=True)),
                ('SUB_TOTAL_CAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_cli', models.ForeignKey(db_column='id_cli', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_pro', models.ForeignKey(db_column='id_pro', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
    ]
