import { palette, typography, spacing, radius, shadows } from "@/constants/Theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.bgSecondary },
  header: {
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    backgroundColor: palette.bgPrimary,
    borderBottomWidth: 1,
    borderBottomColor: palette.borderLight,
  },
  titulo: { fontSize: typography.size["2xl"], fontWeight: typography.weight.bold, color: palette.textPrimary },
  subtitulo: { fontSize: typography.size.sm, color: palette.textMuted, marginTop: 2 },
  lista: { padding: spacing.sm, paddingBottom: spacing.xl },
  card: {
    backgroundColor: palette.bgPrimary,
    borderRadius: radius.lg,
    marginBottom: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
    borderWidth: 1,
    borderColor: palette.borderLight,
    ...shadows.md,
  },
  imagen: { width: 70, height: 70, borderRadius: radius.md, marginRight: spacing.md },
  imagenPlaceholder: {
    width: 70, height: 70, borderRadius: radius.md,
    backgroundColor: palette.actionPrimary,
    alignItems: "center", justifyContent: "center",
    marginRight: spacing.md,
  },
  placeholderText: { color: "#fff", fontSize: typography.size.xl, fontWeight: typography.weight.bold },
  info: { flex: 1, gap: 4 },
  nombre: { fontSize: typography.size.md, fontWeight: typography.weight.semibold, color: palette.textPrimary },
  precio: { fontSize: typography.size.sm, color: palette.textSecondary },
  cantRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  cantBadge: {
    backgroundColor: palette.sky[100],
    borderRadius: radius.full,
    paddingHorizontal: 8, paddingVertical: 2,
  },
  cantText: { fontSize: typography.size.xs, color: palette.sky[700], fontWeight: typography.weight.bold },
  subtotal: { fontSize: typography.size.md, fontWeight: typography.weight.bold, color: palette.pricePrimary },
  emptyContainer: { alignItems: "center", marginTop: 80, gap: 12 },
  emptyText: { fontSize: typography.size.lg, color: palette.textMuted },
  footer: {
    backgroundColor: palette.bgPrimary,
    padding: spacing.base,
    borderTopWidth: 1,
    borderTopColor: palette.borderLight,
    ...shadows.lg,
  },
  totalRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: spacing.md },
  totalLabel: { fontSize: typography.size.lg, color: palette.textSecondary, fontWeight: typography.weight.medium },
  totalValor: { fontSize: typography.size.xl, fontWeight: typography.weight.bold, color: palette.pricePrimary },
  btnCheckout: {
    backgroundColor: palette.actionPrimary,
    borderRadius: radius.lg,
    padding: spacing.base,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    ...shadows.sky,
  },
  btnCheckoutText: { color: "#fff", fontSize: typography.size.md, fontWeight: typography.weight.bold },
});